### ISSUE TITLE
Separate codebase for TableTop and create new repos for Monopoly, Catan, etc.

### ISSUE THREAD

**Issue by qstearns** [andrewjmeier/TableTop.JS#41]
Our sample projects should start to appear more similar to our goal projects. It also may be helpful to separate issue tracking and force more religious use of framework.

- [ ] Investigate javascript compilation tools and the way they are used in other open source projects (Phaser and machina git repos with build instructions might be a good place to start). Example tools that could be appropriate for our project are grunt, gulp, and maybe some extension of npm.
- [ ] Refactor TableTop to behave as a more cohesive library and to maximize practices encouraged by build tools.
- [x] Create new repos for Monopoly, Settlers, and any other games you might be working on (remember to add entire team as contributors and port relevant issues to your repository)
- [ ] Provide documentation and reference links for how to use the build tools that you have decided upon.

Further discussion about pros and cons of various tools should take place below on issue comments.

**Comment by andrewjmeier** [comment]
Definitely still a work in progress. People are still finishing/adding monopoly features and I'm not sure what that will look like so I won't commit anything to this project. I also need to investigate the build tools for the framework a little bit more and then publish it to npm. We're super close though!

**Comment by andrewjmeier** [comment]
@qstearns I think we can probably close this one out
