### ISSUE TITLE
Some messages fail to display completely with new state machine

### ISSUE THREAD

**Issue by qstearns** [andrewjmeier/TableTop.JS#43]
Problem diagnosis is that with old state machine the message was concatenated to in state machine. New state machine errantly rewrote the message from scratch. Temporary fix is in the works.

**Comment by qstearns** [comment]
I think this issue brings up an important question of how we might want messages to be involved in our framework. I think messages and message history are actually an important way for a board game developer to communicate with users. I think we should bake in support for messages at a more fundamental level. Likely starting in the controller level. We should probably also consider how we want to support messages in views

**Comment by andrewjmeier** [comment]
Yeah I would be a fan of some way for any object to post a message somehow

**Comment by andrewjmeier** [comment]
@qstearns this fixed now?

**Comment by qstearns** [comment]
Should be fixed. Closing for now.
