### ISSUE TITLE
Sophisticated messaging module

### ISSUE THREAD

**Issue by qstearns** [andrewjmeier/TableTop.JS#46]
Games generally communicate to players using text-based messages. This is a highly generalizable idea. All game objects should be able to include messages based on what is happening in them and then have those messages displayed to the user. This feature requires a model module that maintains a record of existing messages in a list and somehow captures events emitted from other components of the game and a view module that will display the most recent messages.

- [x] Build a Message module into the model part of the framework
- [x] Build a message view module that displays messages as the game available

**Comment by qstearns** [comment]
Thoughts on model
-----------------

The Message module should probably work as an event consumer where every object can implement a theoretical messageEmitter interface with the only method being emitMessage.

Not sure if we should implement the module to require to explicitly subscribe to messages or automatically consume all messages produced by any message emitter in the game. Not sure if it's best practice in javascript to have something automatically subscribe to events.

Furthermore, if the subscriptions are not automatic, users of the framework could have multiple message models in their games. For instance, in Monopoly we could have a global message module that was subscribed to all public actions and then maybe a private message model for each player that could contain messages that would only be displayed to individual players.

Private messages are also possible with a single global module subscribed to all events if we include permissions in some capacity, but the design might be flawed

**Comment by qstearns** [comment]
Thoughts on view
----------
The view would be easiest to implement as an html div that exists next to the pixi so we could easily include scrollability with the native browser features

**Comment by qstearns** [comment]
The message model from my comment two up might actually be totally useless when I think about it more. It could be best to just have a bunch of message emitters and then print them in the view as they present messages as events –– not necessarily any easier to maintain the messages in memory. Not sure if having a message model is useful. Let me know what you guys think.

**Comment by andrewjmeier** [comment]
@qstearns did we finish this?

**Comment by qstearns** [comment]
We can safely say we finished a v1. We will create new issues for future work
